fieldLayouts:
  89089fc6-cd23-46d8-b875-202d7f0ae871:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f510541a-d81f-41c6-8c85-ef74d4d22e9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9fd8bd98-f8b2-427f-829a-1b6ab2ca699d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f99868b-68a7-4d50-8ab1-df050ca71151
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3915c6ec-8bb1-4b92-afeb-9bd6ddcdb252
        userCondition: null
fs: imageshotel
handle: imageshotel
name: ImagesHotel
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: imageshotel
transformSubpath: ''
