columnSuffix: zbtdgufp
contentColumnType: 'decimal(12,2)'
fieldGroup: f36b1a5f-e3fc-43b7-97f9-ff6764a5cf7f # Common
handle: travelTime
instructions: null
name: 'Travel Time'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
